### ISSUE TITLE
Publish Exponent blog

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website#101]

**Comment by elektramurphy** [comment]
@murphy do you have the doc for this?

**Comment by murphy** [comment]
https://docs.google.com/document/d/1NW9IPlUmIwUanmiNHdHXE6xM_lV-5ZI9piHBWK7zn2A/edit

**Comment by elektramurphy** [comment]
@murphy my fault for not checking emails first. Do we have an image for the blog? Or will we need to mock something up?

**Comment by murphy** [comment]
@elektramurphy you'll need to mock something up. Maybe just Exponen's logo against one of our background colors.

**Comment by elektramurphy** [comment]
@murphy this okay for now? We can always update. 

![Add a heading](https://user-images.githubusercontent.com/57063146/187198792-897dc0da-d7b3-4eb8-b459-e120a3884b2a.png)

**Comment by murphy** [comment]
@elektramurphy please only use their logo. Adding ours makes it seem like a partnership announcement.

**Comment by wcsu95** [comment]
@elektramurphy It's okay i've got it.
@murphy 

https://credmark.com/blog/exponent
