### ISSUE TITLE
Implement new FAQ

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website#105]
https://docs.google.com/document/d/146Q4EVCCXYwjF0eegWQiis-iJOraQ18-MjUP55NkpAU/edit?usp=sharing

I don't know which of you does this so assigning it to both!

**Comment by murphy** [comment]
Damn, I just remembered that we have another FAQ. 

I remember that the original intent was to have a few FAQ items on the website and then use the Gitbook for overflow and questions that required more illustrative answers.

Maintaining something in two places is a pain and likely to lead to mistakes. I'd be in favor of only putting FAQ on website, but you guys may disagree. 

Adding @MattCMK  to the ticket because I know he will have an opinion.

**Comment by MattCMK** [comment]
@murphy For me it depends a little on the context. So we might have a FAQ on the access.credmark.com site to answer questions specifically regarding the account setup, payments, receipts, and creating an API key while the FAQ on the website could be more related to general questions around Credmark and the API products and then linking to the respective Gitbooks

**Comment by murphy** [comment]
Ah, @MattCMK we're talking about two different things. 

The old FAQ on access.credmark.com was necessary and non-standard. Now that people are just going to sign up using Stripe, I don't think we need a FAQ there. When we finally introduce the protocol we definitely will.

I was talking about the fact that we have a FAQ on the website and that after each section we have a "Learn More" button that takes you to the Gitbook-hosted FAQ. For most (all?) FAQ sections it's the same content, which must be frustrating to users. For us, it means we have to keep two things in sync. 

Anyway, I thought the scheme made sense in theory (less maintenance for Wen-Chiao and Elektra) but in practice it's annoying. Updating the website is fast. And we could even move all the content to the CMS so that we could update it without the need to redeploy the site. 
<img width="1117" alt="Screen Shot 2022-09-01 at 09 30 47" src="https://user-images.githubusercontent.com/6160738/187858044-85d9b307-7b83-4ddf-97e1-87a753f1a563.png">

**Comment by MattCMK** [comment]
Ah ok, yeah I would get rid of the Gitbook FAQ and let it reside on the website only. otherwise it feels like a break in the UX

**Comment by murphy** [comment]
OK, glad you agree. 

@elektramurphy therefore remove the "Learn More" button. I'll nuke from Gitbook.

**Comment by elektramurphy** [comment]
@murphy "Learn more" button removed - Any copy updates?

**Comment by murphy** [comment]
@elektramurphy a ton...see Doc in the original ticket description.
