### ISSUE TITLE
Product page gradient + header

### ISSUE THREAD

**Issue by wcsu95** [credmark/credmark-website#123]
The background gradient on the product page doesn't match up with the homepage.
I've adjusted it on figma and I also changed the header color. Please help update this. 

Figma: https://www.figma.com/file/rywMpTbwowB2cf9KkmGHjH/Design%2FWebsite?node-id=1427%3A13794

**Comment by murphy** [comment]
@wcsu95 Did you update what the designers did?

**Comment by murphy** [comment]
I assumed they wanted to create some variety using the same pallet.

**Comment by wcsu95** [comment]
> @wcsu95 Did you update what the designers did?

Yeah I updated it. The designers didn't adjust anything when they working on the product page. They just used the original gradient background that I was working off of. I'm updating it because the scaling of the gradient is off.
