### ISSUE TITLE
Add DebtDAO (https://debtdao.finance/) to list of people who trust us

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website#125]

**Comment by elektramurphy** [comment]
@murphy do we have a logo? they only have png on their website and it's white.

**Comment by murphy** [comment]
@wcsu95 can you get @elektramurphy  what she needs or should I talk to DebtDAO?

**Comment by wcsu95** [comment]
@murphy 
I already provided a copy of the updated partner's section on Figma, including the debtdao logo. 
I think @elektramurphy already updated it yesterday.

**Comment by murphy** [comment]
@wcsu95 🙏🏻

@elektramurphy can you please confirm and close the ticket if so?
