### ISSUE TITLE
Meta image logo

### ISSUE THREAD

**Issue by wcsu95** [credmark/credmark-website#140]
We'll need to update the old logo on the website's meta image

![image](https://user-images.githubusercontent.com/89830616/192415954-ed6fbc56-5c85-404e-95d4-63ea1f91770d.png)

**Comment by elektramurphy** [comment]
@wcsu95 do you have an image for me to update it with?

**Comment by wcsu95** [comment]
![Meta Image](https://user-images.githubusercontent.com/89830616/194796657-248251ef-ef33-4ea7-947d-1445e8d5d19e.png)

Let's use this.
