### ISSUE TITLE
Blog dates should all be ISO: yyyy-mm-dd

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website#148]
I know that sometimes we use slash and sometimes we use dots. That's fine. I don't care as long as it's international format. 

I'm adding @wcsu95 to the ticket in case this is something he can fix.

**Comment by wcsu95** [comment]
> I know that sometimes we use slash and sometimes we use dots. That's fine. I don't care as long as it's international format.
> 
> I'm adding @wcsu95 to the ticket in case this is something he can fix.

There's already a ticket open for this: https://github.com/credmark/credmark-website/issues/95
Should I close this one?

**Comment by murphy** [comment]
Oh, that's funny. I thought there was but couldn't find it. Yea, just mark it as duplicate and close it.
