### ISSUE TITLE
New Team Page 

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website#158]
This is preliminary...please don't execute yet.

Paul Murphy - CEO
Vineet Kumar - CTO
Kunlun Yang - Senior Quant
Ivo Rothschild - Senior Engineer
Asan Tulemis - Risk Management
Matthias Knauth - Product 
Wen-Chiao Su - Marketing
Arunachalam Pandi - DevOps
Kavita Joshi - Data Engineer

Neil Zumwald moves into the Advisor section.

**Comment by murphy** [comment]
OK, @elektramurphy this is good to go.

**Comment by elektramurphy** [comment]
@murphy Can you get me the three names following (Twitter, Linkedin, Picture):

Abhishek Chopra - DevOps
Arun Chalman - DevOps
Kavita Joshi - Data Engineer

**Comment by murphy** [comment]
Arun.
![Arun](https://user-images.githubusercontent.com/6160738/203272193-99107c40-501b-44c7-9e3f-b4b62bfa4274.jpeg)

https://twitter.com/Arunpandi_kr

Don't put his LinkedIn
