### ISSUE TITLE
Update BI Job Description

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website#2]
Note the title change. 

https://docs.google.com/document/d/15Q9OhVxQkbz38mKY8FMir0qDvwqLGHG0zMWgLQ8tJUg/edit

Please let me know when done.

**Comment by murphy** [comment]
@elektramurphy please let me know when this is done so that I can update Lewis, Hong Yuen, and the Russians.

**Comment by elektramurphy** [comment]
@murphy https://github.com/credmark/credmark-website-netlify/pull/6
