### ISSUE TITLE
Make CMK token title clickable

### ISSUE THREAD

**Issue by elektramurphy** [credmark/credmark-website#22]

**Comment by elektramurphy** [comment]
@wcsu95 what do you think re this? I added it based on the heatmap

**Comment by wcsu95** [comment]
I'm thinking it may be distracting, but given that people did try to click it, it might be worth trying.

Where would you want to link this?

**Comment by elektramurphy** [comment]
I noticed we don't really have a blog post purely dedicated to $CMK, maybe we should add this to the agenda and have it click through there ?

**Comment by wcsu95** [comment]
@elektramurphy 
Yeah we don't
https://coinmarketcap.com/currencies/credmark/
I'm thinking we can use this for the time being until we decide whether it'll be worthwhile to write a dedicated piece on the token.
