### ISSUE TITLE
Core team

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-website#29]
Please:

* Replace Stijn with Mark (and make sure Mark has updated his LinkedIn)
* Add Punit Kumar (punit@credmark.com)
* Add Kunlun Yang (kunlun@credmark.com)

**Comment by murphy** [comment]
Also these title changes:

* Neil » Technology
* Momin » Growth
* Collier » Partnerships

And these additions I forgot about:

* Vineet Kumar (vineet@altercode.xyz) - Technology
* Ivo Rothschild - Technology (Get his OK before doing it)
* Yourself - Technology (unless you think it's a problem with your company in which case you should do it as an anon like Peter)

**Comment by elektramurphy** [comment]
@markvalentine do you have an image I can use for the team page ?
