### ISSUE TITLE
Minor modification to blog

### ISSUE THREAD

**Issue by wcsu95** [credmark/credmark-website#76]
![image](https://user-images.githubusercontent.com/89830616/168318608-5c13b0fe-b00f-4d1a-8903-f0add1316e65.png)
Can we center the title/subtitle/writer/date etc?

![image](https://user-images.githubusercontent.com/89830616/168318791-09de3993-4402-465d-9b3b-15a7a31ab8ae.png)
1. Box seems a bit weird with the text squished next to it
2. Embed URLs look really thin and not obvious

**Comment by elektramurphy** [comment]
@wcsu95 I've update your point 1 and 2 but for this request 'Can we center the title/subtitle/writer/date etc?' you'll need to check with Mark because this is his design
