### ISSUE TITLE
Add additional title tag

### ISSUE THREAD

**Issue by wcsu95** [credmark/credmark-website#78]
![image](https://user-images.githubusercontent.com/89830616/169558325-1b1f25ca-4b59-4fbc-871a-191daa2e76fd.png)
![image](https://user-images.githubusercontent.com/89830616/169558296-f3e2b478-cb2b-496e-abe6-e14a27291e6e.png)

Credmark - Where DeFi Builds Financial Models

**Comment by elektramurphy** [comment]
@wcsu95 should this be updated for the new design?
